### ISSUE TITLE
dist should be updated

### ISSUE THREAD

**Issue by industral** [pldespaigne/content-hash#20]
variable `package` was moved to `packageJson`, but not for `dist`. Error with `rollupjs` builder, that `package` is reserved word. Need to update build and deploy a new version in npm.

**Comment by pldespaigne** [comment]
Ok I'm on it !

**Comment by pldespaigne** [comment]
should be ok now ✔️
could you confirm ?

**Comment by industral** [comment]
wow, that was fast :) Yeah, it works now. Thanks!
