### ISSUE TITLE
IPNS support

### ISSUE THREAD

**Issue by makoto** [pldespaigne/content-hash#25]
Now that multicodec merged ipns support, can you also add it to the lib?
https://github.com/multiformats/multicodec/pull/136

**Comment by pldespaigne** [comment]
Hi @makoto 😄 I'm planing on implementing a general encoding function (see #17 ), do you think this would address your issue ?

**Comment by pldespaigne** [comment]
Hi @makoto ! The code is ready, just waiting for [js-multicodec #36](https://github.com/multiformats/js-multicodec/issues/36) to include latest changes to their npm package

**Comment by pldespaigne** [comment]
merge ! and publish to npm v2.4.2
