### ISSUE TITLE
get list of all adresses on bitcoin block chain

### ISSUE THREAD

**Issue by MohammadAsadolahi** [pldespaigne/content-hash#50]
hi im asking about your blk parser in this link:
https://github.com/pldespaigne/blk_parser

how can i get all addresses on bitcoin blockchain i mean every address that comited a transaction on blockchain no matter it has balance or not?
for example get list of all addresses in text file
i want to get all adresses that has any kind of transaction on blockchain of all time
thank you

**Comment by MohammadAsadolahi** [comment]
and your file only gives sender addresses i need receiver addresses too in simple word all addresses that has any transaction anytime.
can i leave my email to ask my questions from you?
or how can i contact you

**Comment by pldespaigne** [comment]
Hi @mohammadAsadolahi  👋 
Thanks for you interest in my Blk_parser project !

Unfortunately I don't maintain it anymore.
If you just want to get a dataset with all Bitcoin address, I think the simplest solution would be write a small script that use per-existing Blockchain data. You should have a look on Kaggle for that.

I hope my answer helps you.
If you need more info you can DM me on Twitter @pldespaigne
